import pandas as pd
import h5py

neutrons_ess = pd.read_excel('dcfs.xlsx', sheet_name='ESS_neutrons', usecols=(0, 1), skiprows=2)
photons_ess = pd.read_excel('dcfs.xlsx', sheet_name='ESS_photons', usecols=(0, 1), skiprows=2)
neutrons_ncrp38 = pd.read_excel('dcfs.xlsx', sheet_name='NCRP38_neutrons', usecols=(0, 1), skiprows=2)
protons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_protons', usecols=(0, 1, 2, 3, 4, 5, 6), skiprows=3)
neutrons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_neutrons', usecols=(0, 1, 2, 3, 4, 5, 6), skiprows=3)
photons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_photons', usecols=(0, 1, 2, 3, 4, 5, 6), skiprows=3)
electrons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_electrons', usecols=(0, 1, 2, 3), skiprows=3)
positrons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_positrons', usecols=(0, 1, 2, 3), skiprows=3)
neg_muons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_muon-', usecols=(0, 1, 2, 3), skiprows=3)
pos_muons_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_muon+', usecols=(0, 1, 2, 3), skiprows=3)
neg_pions_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_pion-', usecols=(0, 1, 2, 3), skiprows=3)
pos_pions_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_pion+', usecols=(0, 1, 2, 3), skiprows=3)
helium_icrp116 = pd.read_excel('dcfs.xlsx', sheet_name='ICRP116_helium', usecols=(0, 1, 2, 3), skiprows=3)

dcffile = h5py.File('DCFfile.h5', 'w')
ess = dcffile.create_group('ESS')
ncrp38 = dcffile.create_group('NCRP38')
icrp116 = dcffile.create_group('ICRP116')
ess.create_dataset('neutrons', data=neutrons_ess)
ess.create_dataset('photons', data=photons_ess)
ncrp38.create_dataset('neutrons', data=neutrons_ncrp38)
icrp116.create_dataset('protons', data=protons_icrp116)
icrp116.create_dataset('neutrons', data=neutrons_icrp116)
icrp116.create_dataset('photons', data=photons_icrp116)
icrp116.create_dataset('electrons', data=electrons_icrp116)
icrp116.create_dataset('positrons', data=positrons_icrp116)
icrp116.create_dataset('muon-', data=neg_muons_icrp116)
icrp116.create_dataset('muon+', data=pos_muons_icrp116)
icrp116.create_dataset('pion-', data=neg_pions_icrp116)
icrp116.create_dataset('pion+', data=pos_pions_icrp116)
icrp116.create_dataset('helium', data=helium_icrp116)

dcffile.close()
